services:
  database:
    image: postgres:18
    container_name: numer_database
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgressql/data
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5454:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: numer_backend
    restart: "always"
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8000:8000"
    
  frontend:
    build:
      context: ./frontend
    container_name: numer_frontend
    restart: "always"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
volumes:
  postgres_data: